import Head from "next/head";
import { HomePage } from "../components/home/home-page";
//import { Geist, Geist_Mono } from "next/font/google";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export default function Home({ data }) {
  /*
  function getServerSideProps() {
    return {
      props: {
        title: "Hello Everyone!",
      },
    };
  }
    */
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <HomePage data={data} />


    </div>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("../../data/data.json");

  return {
    props: {
      data: events_categories,
    },
  };
}
